openapi: 3.0.1
info:
  title: Log_API
  description: API Definition of Log_API
  version: 1.0.0
servers:
- url: http://localhost:8290/log
paths:
  /message:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
